import "./globals.css";

import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import { Roboto_Mono } from "next/font/google";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <Header />
        <body className={`${inter.className} antialiased`}>
          {children}
        </body>
        <Footer />
      </ThemeProvider>
    </html>
  );
}
